stages:
  download_data:
    cmd: python scripts/download_data.py
    outs:
      - data/raw/california_housing.csv
  
  preprocess_data:
    cmd: python -m src.data.preprocessing
    deps:
      - data/raw/california_housing.csv
      - src/data/preprocessing.py
    outs:
      - data/processed/X_train.npy
      - data/processed/X_test.npy
      - data/processed/y_train.npy
      - data/processed/y_test.npy
      - data/processed/feature_names.csv
      - data/processed/preprocessor.pkl