global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # California Housing MLOps API
  - job_name: 'california-housing-api'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    
  # MLflow UI
  - job_name: 'mlflow-ui'
    static_configs:
      - targets: ['localhost:5001']
    scrape_interval: 30s

  # Node Exporter (if you want system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s 